
include: package:lint/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore
    always_specify_types: true
    unused_import: error
    avoid_relative_lib_imports: true
    sort_pub_dependencies: false
