name: exposure
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^2.3.0
  cloud_firestore: ^2.4.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.2
  dio: ^4.0.0
  equatable: ^2.0.3
  firebase_auth: ^3.1.0
  firebase_core: ^1.6.0
  flutter_bloc: ^7.1.0
  flutter_svg: ^0.22.0
  freezed_annotation: ^0.14.2
  get_it: ^7.2.0
  injectable: ^1.4.1
  internet_connection_checker: ^0.0.1+2
  intl: ^0.17.0
  time_range_picker: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^2.3.0
  build_runner:
  flutter_launcher_icons: ^0.9.1
  freezed: ^0.14.2
  injectable_generator: ^1.4.1
  lint: ^1.5.3
  mocktail: ^0.1.4

flutter_icons:
  image_path: "assets/icon/app-icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - secret.json
    - images/server_error.svg
    - images/location_not_found.svg
    - assets/icon/app-icon.png

dependency_overrides:
  meta: ^1.7.0
  test_api: ^0.4.2
