name: CD

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Build Apps
    runs-on: macos-10.15
    defaults:
      run:
        working-directory: src/exposure
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.3'
      - run: flutter pub get
      - run: flutter test
      - name: Build Android App
        run: flutter build apk --obfuscate --split-debug-info --split-per-abi
      - name: Build iOS App
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Create release name and tag
        run: echo "APP_VERSION=release_$(date +'%Y-%m-%d_%H-%m-%S')" >> $GITHUB_ENV
      - name: Release builds
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.APP_VERSION }}
          name: ${{ env.APP_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: 'src/exposure/build/app/outputs/apk/release/*.apk,src/exposure/build/ios/iphoneos/app.ipa'
          artifactErrorsFailBuild: true
